[tool.black]
line-length = 100
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true
multi_line_output = 3
include_trailing_comma = true

[tool.flake8]
max-line-length = 100
exclude = ["data", ".venv", "__pycache__"]
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = 3.9
ignore_missing_imports = true
strict_optional = true
disallow_untyped_defs = true
check_untyped_defs = true
