[tool.black]
line-length = 88
target-version = ["py39"]
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.mypy_cache
  | \.pytest_cache
  | build
  | dist
  | data
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["src"]
known_third_party = ["pandas", "numpy", "seaborn", "pytest"]
skip = ["venv", ".venv", "data", "build"]

[tool.flake8]
max-line-length = 88
exclude = 
  .git,
  __pycache__,
  .venv,
  venv,
  build,
  dist,
  data/
select = B,C,E,F,W,T4,B9
ignore = E203, E266, E501, W503
show-source = true
per-file-ignores = 
    tests/*: S101

[tool.mypy]
python_version = 3.9
ignore_missing_imports = true
strict = true
show_error_codes = true
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
files = ["src", "tests"]
