version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: logs/pipeline.log
    mode: a
    encoding: utf-8

loggers:
  # Root logger
  '':
    level: INFO
    handlers: [console, file]

  # Specific module logging levels (optional)
  ingestion:
    level: INFO
    handlers: [console, file]
    propagate: no

  bronze_to_silver:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  silver_to_gold:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  visualization:
    level: INFO
    handlers: [console, file]
    propagate: no

  utils:
    level: WARNING
    handlers: [console, file]
    propagate: no
